site: EinsteinPy

ga_id: "UA-143004589-1"

collections:
  - features
  - goals
  - scenarios
  - users

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap
